CAMERA_ID = 0

FRAME_WIDTH = 640
FRAME_HEIGHT = 480

FALL_ANGLE_THRESHOLD = 60
FALL_FRAME_THRESHOLD = 15

SNAPSHOT_FOLDER = "../snapshots"
LOG_FILE = "../logs/events.csv"

ALERT_COOLDOWN_SECONDS = 10
